Department_chart:
 Department_replicaCount: 1
 Department_repository: dariofrongillo/department-ws
 Department_tag: 0.0.1
 build:
  enabled: false
  
Staff_chart:
 Staff_replicaCount: 1
 Staff_repository: dariofrongillo/staff-ws
 Staff_tag: 0.0.1
 build:
  enabled: false
